// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjsmalnhosfsmwlvwzbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqc21hbG5ob3Nmc213bHZ3emJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjAwODEsImV4cCI6MjA2NDM5NjA4MX0.n8s3sIxBpnPLYidMCjnwrOkZJ84_rP3kIA2B-encbNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);